/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Metodos;
import Modelo.Horario;
import Modelo.Medico;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author benja
 */
public class HoraDisponible2 extends javax.swing.JFrame {

    /**
     * Creates new form HoraDisponible2
     */
    public HoraDisponible2() {
        initComponents();
        setSize(900,600);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn_Mostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_horarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(167, 219, 216));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_Mostrar.setText("Mostrar");
        jbtn_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_MostrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 250, 60));

        jtbl_horarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora", "Fecha", "Rut Medico", "Nombre", "Especialidad", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbl_horarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 680, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_MostrarActionPerformed
        // TODO add your handling code here:
        
        String numrut = "", estado,hora,nombre,especialidad;
        int dia,mes,ano;
        
        Metodos me = new Metodos();
        
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_horarios.getModel();
        
        ArrayList<Horario> lista_hora = me.obtenerHorarios();
        
        
        
        for (Horario horario1 : lista_hora) {
            
            numrut = horario1.getNumRut();
            estado = horario1.getEstado();
            hora = horario1.getHora();
            dia = horario1.getDia();
            mes = horario1.getMes();
            ano = horario1.getAno();
            
            if ("1".equals(estado)) {
                estado = "Disponible";
            } else {
                estado = "Reservado";
            }
            
            ArrayList<Medico> lista_medico = me.buscarMedico(numrut);
            Medico medico = me.buscarMedicoPorRut(lista_medico, numrut);
            
            nombre = medico.getNombre();
            especialidad = medico.getDescEspecialidad();
            modelo.addRow(new Object []{hora,dia+"/"+mes+"/"+ano,numrut,nombre,especialidad,estado});
            
            
            
        }
        
        
        
        
    }//GEN-LAST:event_jbtn_MostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoraDisponible2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoraDisponible2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoraDisponible2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoraDisponible2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoraDisponible2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_Mostrar;
    private javax.swing.JTable jtbl_horarios;
    // End of variables declaration//GEN-END:variables
}
