/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Metodos;
import Modelo.Especialidad;
import Modelo.Horario;
import Modelo.Medico;
import Modelo.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author benja
 */
public class HoraDisponible extends javax.swing.JFrame {

    /**
     * Creates new form HoraDisponible
     */
    Metodos me = new Metodos();
    public HoraDisponible() {
        initComponents();
        setSize(900,600);
        setResizable(false);
        setLocationRelativeTo(null);
        me.RellenarCombo("ESPECIALIDAD", "DESC_ESPECIALIDAD", jcbx_especialidad);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Disponible = new javax.swing.JTable();
        jbtn_Mostrar = new javax.swing.JButton();
        jtxt_fecha = new javax.swing.JTextField();
        jtxt_hora = new javax.swing.JTextField();
        jtxt_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxt_estado = new javax.swing.JTextField();
        jcbx_especialidad = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtxt_rutcliente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_cliente = new javax.swing.JTable();
        jbtn_reservar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtxt_rutdoc = new javax.swing.JTextField();
        jtxt_idHora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(224, 228, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(224, 228, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Reserva de Citas");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 900, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Horas Disponibles");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        jPanel4.setBackground(new java.awt.Color(167, 219, 216));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtb_Disponible.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Horario", "Fecha", "Hora", "Rut Doctor", "Nombre ", "Especialidad", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtb_Disponible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_DisponibleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_Disponible);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 580, 230));

        jbtn_Mostrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtn_Mostrar.setText("Mostrar");
        jbtn_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_MostrarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtn_Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 100, 20));

        jtxt_fecha.setEditable(false);
        jtxt_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_fechaActionPerformed(evt);
            }
        });
        jPanel4.add(jtxt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 160, -1));

        jtxt_hora.setEditable(false);
        jPanel4.add(jtxt_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 160, -1));

        jtxt_nombre.setEditable(false);
        jPanel4.add(jtxt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Fecha:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Hora:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Estado:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        jtxt_estado.setEditable(false);
        jPanel4.add(jtxt_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 160, -1));

        jcbx_especialidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbx_especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione --" }));
        jPanel4.add(jcbx_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 220, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Rut Cliente:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        jPanel4.add(jtxt_rutcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 240, -1));

        jtbl_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fecha Nacimiento", "Correo", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtbl_cliente);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 660, 50));

        jbtn_reservar.setText("Reservar");
        jbtn_reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_reservarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtn_reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("RUT:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        jtxt_rutdoc.setEditable(false);
        jPanel4.add(jtxt_rutdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 160, -1));
        jPanel4.add(jtxt_idHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 160, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Id Hora:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_MostrarActionPerformed
        // TODO add your handling code here:
        
        String numrut,estado,hora,nombre = "",especialidad;
        int dia,mes,ano,idHorario;
        
        DefaultTableModel modelo = (DefaultTableModel) this.jtb_Disponible.getModel();
        
        ArrayList<Horario> lista = me.obtenerHorarios();
        ArrayList<Medico> listaMedicos = me.obtenerTodosLosMedicos();
        
        modelo.setRowCount(0);
        
        for (Horario horario : lista) {
            numrut = horario.getNumRut();
            estado = horario.getEstado();
            hora = horario.getHora();
            dia = horario.getDia();
            mes = horario.getMes();
            ano = horario.getAno();
            idHorario = horario.getIdHorario();
            
            if ("1".equals(estado)) {
                estado = "Disponible"; 
            }else{
                estado = "Reservado";
            }
            Medico medico = null;
            for (Medico med : listaMedicos) {
                if (med.getNumRut().equals(numrut)) {
                    medico = med;
                    break;
                }
            }
            
            nombre = medico.getNombre();
            especialidad = medico.getDescEspecialidad();
            
            if (jcbx_especialidad.getSelectedItem().equals(especialidad)) {
                modelo.addRow(new Object [] {idHorario,dia+"/"+mes+"/"+ano,hora,numrut,nombre,especialidad,estado});
            }
        } 
    }//GEN-LAST:event_jbtn_MostrarActionPerformed

    private void jtb_DisponibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_DisponibleMouseClicked
        // TODO add your handling code here:
        
        int fila = jtb_Disponible.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se eligio fila");
            
        }else{
            int idHora = (Integer) jtb_Disponible.getValueAt(fila, 0);
            String fecha = (String) jtb_Disponible.getValueAt(fila,1);
            String hora = (String) jtb_Disponible.getValueAt(fila,2);
            String RutDoc = (String) jtb_Disponible.getValueAt(fila,3);
            String nombre = (String) jtb_Disponible.getValueAt(fila,4);
            String especialidad = (String) jtb_Disponible.getValueAt(fila,5);
            String estado = (String) jtb_Disponible.getValueAt(fila,6);
            
            jtxt_idHora.setText(String.valueOf(idHora));
            jtxt_estado.setText(estado);
            jtxt_fecha.setText(fecha);
            jtxt_nombre.setText(nombre);
            jtxt_hora.setText(hora); 
            jtxt_rutdoc.setText(RutDoc);
        }
        
        
    }//GEN-LAST:event_jtb_DisponibleMouseClicked

    private void jtxt_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_fechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int dia,mes,ano,telefono;
        String rut,nombre,correo,fecNac;
        
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_cliente.getModel();
        
        modelo.setRowCount(0);
        
        Usuario usuario = me.buscarUsuario(this.jtxt_rutcliente.getText());
        
        if (usuario != null) {
            dia = usuario.getDia();
            mes = usuario.getMes();
            ano = usuario.getAno();
            fecNac = dia+"-"+mes+"-"+ano;
            nombre = usuario.getNombre();
            correo = usuario.getCorreo();
            telefono = usuario.getNumTelefono();
            
            modelo.addRow(new Object [] {nombre,fecNac,correo,telefono});
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Usuario no existe en los registros","No Encontrado",0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtn_reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_reservarActionPerformed
        // TODO add your handling code here:
        
        int dia = 0;
        int mes = 0;
        int ano = 0;
        String fecha = jtxt_fecha.getText();
        int idHora = Integer.parseInt(this.jtxt_idHora.getText());
        
        
        try {
            String [] partesfecha = fecha.split("/");
            dia = Integer.parseInt(partesfecha[0]);
            mes = Integer.parseInt(partesfecha[1]);
            ano = Integer.parseInt(partesfecha[2]);
        } catch (Exception e) {
        }
        
        if (jtxt_nombre == null) {
            JOptionPane.showMessageDialog(null, "Seleccione una hora primero ","Error",0);  
        }
        if (jtxt_estado.getText().equalsIgnoreCase("Reservado")) {
            JOptionPane.showMessageDialog(null, "Seleccione una hora disponible ","Error",0);  
        }
        else
        {
            String rutDoc = jtxt_rutdoc.getText();
        me.ReservarHora(rutDoc, dia, mes, ano,jtxt_hora.getText());
        
        me.AgregarCita(idHora,jtxt_fecha.getText(), jtxt_rutdoc.getText(), jtxt_rutcliente.getText(), jtxt_hora.getText());
        
        JOptionPane.showMessageDialog(null, "Reserva Médica Realizada","Reserva",1);
        }
        

        
      
    }//GEN-LAST:event_jbtn_reservarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoraDisponible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoraDisponible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoraDisponible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoraDisponible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoraDisponible().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtn_Mostrar;
    private javax.swing.JButton jbtn_reservar;
    private javax.swing.JComboBox<String> jcbx_especialidad;
    private javax.swing.JTable jtb_Disponible;
    private javax.swing.JTable jtbl_cliente;
    private javax.swing.JTextField jtxt_estado;
    private javax.swing.JTextField jtxt_fecha;
    private javax.swing.JTextField jtxt_hora;
    private javax.swing.JTextField jtxt_idHora;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_rutcliente;
    private javax.swing.JTextField jtxt_rutdoc;
    // End of variables declaration//GEN-END:variables

   
}
